"""initial tables

Revision ID: 24dcf158f3ca
Revises: 
Create Date: 2026-02-09 19:36:15.139801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dcf158f3ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cashback_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('claimed_by', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashback_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashback_assets_status'), ['status'], unique=False)

    op.create_table('cashback_claims_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['cashback_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashback_claims_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashback_claims_ledger_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashback_claims_ledger_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashback_claims_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashback_claims_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_cashback_claims_ledger_asset_id'))

    op.drop_table('cashback_claims_ledger')
    with op.batch_alter_table('cashback_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashback_assets_status'))

    op.drop_table('cashback_assets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
